---
# =========================================================
# Jenkins Installation
# =========================================================
jenkins_repo_url: "https://pkg.jenkins.io/rpm-stable/jenkins.repo"
jenkins_key_url: "https://pkg.jenkins.io/rpm-stable/jenkins.io-2026.key"
jenkins_port: 8080


# =========================================================
# Jenkins Plugins
# =========================================================
jenkins_plugins:
  - git
  - github
  - workflow-aggregator
  - credentials-binding
  - ssh-credentials
  - configuration-as-code


# =========================================================
# Jenkins Configuration as Code
# =========================================================
jenkins_casc_dir: "/var/lib/jenkins/casc_configs"
jenkins_casc_file: "/var/lib/jenkins/casc_configs/jenkins.yaml"

jenkins_num_executors: 2
jenkins_system_message: "NeuroPlan CI/CD Jenkins - Managed by Ansible/JCasC"
