---
# Kubernetes API VIP
keepalived_router_id: "lb1"
keepalived_state: "MASTER"
keepalived_interface: "ens224"

keepalived_virtual_router_id: 34
keepalived_priority: 110

keepalived_src_ip: "192.168.34.11"
keepalived_peer_ip: "192.168.34.12"

keepalived_api_vip: "192.168.34.100"


# Service VIP
service_vip_state: "MASTER"
service_vip_interface: "ens192"
service_vip_virtual_router_id: 24
service_vip_priority: 110

service_vip_src_ip: "192.168.24.11"
service_vip_peer_ip: "192.168.24.12"

service_vip_address: "192.168.24.100"
