# 1차 프로젝트 - Ansible Inventory
# Ansible SSH는 Management Network(192.168.14.0/24)만 사용

[loadbalancers]
lb1 ansible_host=192.168.14.11
lb2 ansible_host=192.168.14.12

[devops_nodes]
devops ansible_host=192.168.14.21 ansible_connection=local

[control_plane]
cp1 ansible_host=192.168.14.31
cp2 ansible_host=192.168.14.32
cp3 ansible_host=192.168.14.33

[workers]
worker1 ansible_host=192.168.14.41
worker2 ansible_host=192.168.14.42
worker3 ansible_host=192.168.14.43

[database]
db-primary ansible_host=192.168.14.51
db-replica ansible_host=192.168.14.52

[nfs_nodes]
nfs ansible_host=192.168.14.61

[infra_nodes]
infra ansible_host=192.168.14.62


# DevOps VM을 제외한 원격 관리 대상
[managed_servers:children]
loadbalancers
control_plane
workers
database
nfs_nodes
infra_nodes


# 프로젝트 전체 VM
[project_nodes:children]
devops_nodes
managed_servers


# 원격 서버는 ansible 계정 사용
[managed_servers:vars]
ansible_user=ansible