---
helm_version: "v3.18.4"
helm_os: "linux"
helm_arch: "amd64"

helm_archive: "helm-{{ helm_version }}-{{ helm_os }}-{{ helm_arch }}.tar.gz"
helm_download_url: "https://get.helm.sh/{{ helm_archive }}"

helm_install_dir: "/opt/helm-{{ helm_version }}"
helm_binary_path: "/usr/local/bin/helm"
