---
keepalived_router_id: "lb1"
keepalived_state: "MASTER"
keepalived_interface: "ens224"

keepalived_virtual_router_id: 34
keepalived_priority: 110

keepalived_src_ip: "192.168.34.11"
keepalived_peer_ip: "192.168.34.12"

keepalived_api_vip: "192.168.34.100"
