---
- name: Configure DevOps CI Server
  hosts: devops_nodes
  become: true

  roles:
    - java
    - maven
    - nodejs
    - docker

    - role: kubectl_client
      tags:
        - kubectl_client

    - jenkins
    - helm
    - argocd
