---
# ------------------------------------------------------------
# 1. Central NTP Server - Infra
# ------------------------------------------------------------
- name: Configure Infra central NTP server
  hosts: infra_nodes
  become: true

  vars:
    ntp_mode: server

  roles:
    - ntp


# ------------------------------------------------------------
# 2. NTP Clients
# ------------------------------------------------------------
- name: Configure NTP clients
  hosts: all:!infra_nodes
  become: true

  vars:
    ntp_mode: client

  roles:
    - ntp
